// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package register

import (
	"github.com/Kurichi/plesio-monorepo/services/item/adapter/grpc"
	"github.com/Kurichi/plesio-monorepo/services/item/adapter/pubsub"
	"github.com/Kurichi/plesio-monorepo/services/item/application"
	"github.com/Kurichi/plesio-monorepo/services/item/domain"
	"github.com/Kurichi/plesio-monorepo/services/item/infra"
	"github.com/Kurichi/plesio-monorepo/services/item/pkg/config"
	"github.com/Kurichi/plesio-monorepo/services/item/pkg/database"
	"github.com/Kurichi/plesio-monorepo/services/item/pkg/treepb"
)

// Injectors from wire.go:

func New() *Server {
	dbConfig := config.NewDBConfig()
	db := database.New(dbConfig)
	itemRepository := infra.NewItemRepository(db)
	inventoryRepository := infra.NewInventoryRepository(db)
	itemService := domain.NewItemService(inventoryRepository)
	treeServiceClient := treepb.New()
	treeService := infra.NewTreeService(treeServiceClient)
	itemUsecase := application.NewItemUsecase(itemRepository, inventoryRepository, itemService, db, treeService)
	itemServiceServer := api.NewItemController(itemUsecase)
	server := Register(itemServiceServer)
	itemController := pubsub.NewItemController(itemUsecase)
	registerPbServer := Subscriber(itemController)
	registerServer := NewServer(server, registerPbServer)
	return registerServer
}
