// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: schema/tree.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlantTreeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *PlantTreeRequest) Reset() {
	*x = PlantTreeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_tree_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlantTreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlantTreeRequest) ProtoMessage() {}

func (x *PlantTreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tree_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlantTreeRequest.ProtoReflect.Descriptor instead.
func (*PlantTreeRequest) Descriptor() ([]byte, []int) {
	return file_schema_tree_proto_rawDescGZIP(), []int{0}
}

func (x *PlantTreeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTreeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetTreeRequest) Reset() {
	*x = GetTreeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_tree_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTreeRequest) ProtoMessage() {}

func (x *GetTreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tree_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTreeRequest.ProtoReflect.Descriptor instead.
func (*GetTreeRequest) Descriptor() ([]byte, []int) {
	return file_schema_tree_proto_rawDescGZIP(), []int{1}
}

func (x *GetTreeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTreeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tree *Tree `protobuf:"bytes,1,opt,name=tree,proto3" json:"tree,omitempty"`
}

func (x *GetTreeResponse) Reset() {
	*x = GetTreeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_tree_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTreeResponse) ProtoMessage() {}

func (x *GetTreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tree_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTreeResponse.ProtoReflect.Descriptor instead.
func (*GetTreeResponse) Descriptor() ([]byte, []int) {
	return file_schema_tree_proto_rawDescGZIP(), []int{2}
}

func (x *GetTreeResponse) GetTree() *Tree {
	if x != nil {
		return x.Tree
	}
	return nil
}

type GetTreeRankingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit int32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *GetTreeRankingRequest) Reset() {
	*x = GetTreeRankingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_tree_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTreeRankingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTreeRankingRequest) ProtoMessage() {}

func (x *GetTreeRankingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tree_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTreeRankingRequest.ProtoReflect.Descriptor instead.
func (*GetTreeRankingRequest) Descriptor() ([]byte, []int) {
	return file_schema_tree_proto_rawDescGZIP(), []int{3}
}

func (x *GetTreeRankingRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetTreeRankingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ranking []*Tree `protobuf:"bytes,1,rep,name=ranking,proto3" json:"ranking,omitempty"`
}

func (x *GetTreeRankingResponse) Reset() {
	*x = GetTreeRankingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_tree_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTreeRankingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTreeRankingResponse) ProtoMessage() {}

func (x *GetTreeRankingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tree_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTreeRankingResponse.ProtoReflect.Descriptor instead.
func (*GetTreeRankingResponse) Descriptor() ([]byte, []int) {
	return file_schema_tree_proto_rawDescGZIP(), []int{4}
}

func (x *GetTreeRankingResponse) GetRanking() []*Tree {
	if x != nil {
		return x.Ranking
	}
	return nil
}

type Tree struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Stage      int32  `protobuf:"varint,2,opt,name=stage,proto3" json:"stage,omitempty"`
	Water      int32  `protobuf:"varint,3,opt,name=water,proto3" json:"water,omitempty"`
	Fertilizer int32  `protobuf:"varint,4,opt,name=fertilizer,proto3" json:"fertilizer,omitempty"`
	PlantAt    int64  `protobuf:"varint,5,opt,name=plant_at,json=plantAt,proto3" json:"plant_at,omitempty"`
}

func (x *Tree) Reset() {
	*x = Tree{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_tree_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tree) ProtoMessage() {}

func (x *Tree) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tree_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tree.ProtoReflect.Descriptor instead.
func (*Tree) Descriptor() ([]byte, []int) {
	return file_schema_tree_proto_rawDescGZIP(), []int{5}
}

func (x *Tree) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tree) GetStage() int32 {
	if x != nil {
		return x.Stage
	}
	return 0
}

func (x *Tree) GetWater() int32 {
	if x != nil {
		return x.Water
	}
	return 0
}

func (x *Tree) GetFertilizer() int32 {
	if x != nil {
		return x.Fertilizer
	}
	return 0
}

func (x *Tree) GetPlantAt() int64 {
	if x != nil {
		return x.PlantAt
	}
	return 0
}

type GrowthRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Target string `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"` // 'water' or 'fertilizer'
	Amount int32  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *GrowthRequest) Reset() {
	*x = GrowthRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_tree_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrowthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrowthRequest) ProtoMessage() {}

func (x *GrowthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tree_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrowthRequest.ProtoReflect.Descriptor instead.
func (*GrowthRequest) Descriptor() ([]byte, []int) {
	return file_schema_tree_proto_rawDescGZIP(), []int{6}
}

func (x *GrowthRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GrowthRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *GrowthRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type GrowthResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tree *Tree `protobuf:"bytes,1,opt,name=tree,proto3" json:"tree,omitempty"`
}

func (x *GrowthResponse) Reset() {
	*x = GrowthResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_tree_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrowthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrowthResponse) ProtoMessage() {}

func (x *GrowthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tree_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrowthResponse.ProtoReflect.Descriptor instead.
func (*GrowthResponse) Descriptor() ([]byte, []int) {
	return file_schema_tree_proto_rawDescGZIP(), []int{7}
}

func (x *GrowthResponse) GetTree() *Tree {
	if x != nil {
		return x.Tree
	}
	return nil
}

var File_schema_tree_proto protoreflect.FileDescriptor

var file_schema_tree_proto_rawDesc = []byte{
	0x0a, 0x11, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2f, 0x74, 0x72, 0x65, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x04, 0x74, 0x72, 0x65, 0x65, 0x22, 0x22, 0x0a, 0x10, 0x50, 0x6c, 0x61,
	0x6e, 0x74, 0x54, 0x72, 0x65, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x20, 0x0a,
	0x0e, 0x47, 0x65, 0x74, 0x54, 0x72, 0x65, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x31, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x54, 0x72, 0x65, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1e, 0x0a, 0x04, 0x74, 0x72, 0x65, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0a, 0x2e, 0x74, 0x72, 0x65, 0x65, 0x2e, 0x54, 0x72, 0x65, 0x65, 0x52, 0x04, 0x74, 0x72,
	0x65, 0x65, 0x22, 0x2d, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x54, 0x72, 0x65, 0x65, 0x52, 0x61, 0x6e,
	0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x22, 0x3e, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x54, 0x72, 0x65, 0x65, 0x52, 0x61, 0x6e, 0x6b,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x07, 0x72,
	0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x74,
	0x72, 0x65, 0x65, 0x2e, 0x54, 0x72, 0x65, 0x65, 0x52, 0x07, 0x72, 0x61, 0x6e, 0x6b, 0x69, 0x6e,
	0x67, 0x22, 0x7d, 0x0a, 0x04, 0x54, 0x72, 0x65, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x74, 0x61, 0x67, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x77, 0x61, 0x74, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x77, 0x61, 0x74, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x66, 0x65, 0x72, 0x74, 0x69, 0x6c, 0x69,
	0x7a, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x66, 0x65, 0x72, 0x74, 0x69,
	0x6c, 0x69, 0x7a, 0x65, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x6e, 0x74, 0x5f, 0x61,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x6e, 0x74, 0x41, 0x74,
	0x22, 0x58, 0x0a, 0x0d, 0x47, 0x72, 0x6f, 0x77, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x30, 0x0a, 0x0e, 0x47, 0x72,
	0x6f, 0x77, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x04,
	0x74, 0x72, 0x65, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x74, 0x72, 0x65,
	0x65, 0x2e, 0x54, 0x72, 0x65, 0x65, 0x52, 0x04, 0x74, 0x72, 0x65, 0x65, 0x32, 0x90, 0x03, 0x0a,
	0x0b, 0x54, 0x72, 0x65, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3b, 0x0a, 0x08,
	0x49, 0x6e, 0x69, 0x74, 0x54, 0x72, 0x65, 0x65, 0x12, 0x16, 0x2e, 0x74, 0x72, 0x65, 0x65, 0x2e,
	0x50, 0x6c, 0x61, 0x6e, 0x74, 0x54, 0x72, 0x65, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x15, 0x2e, 0x74, 0x72, 0x65, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x72, 0x65, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x09, 0x50, 0x6c, 0x61,
	0x6e, 0x74, 0x54, 0x72, 0x65, 0x65, 0x12, 0x16, 0x2e, 0x74, 0x72, 0x65, 0x65, 0x2e, 0x50, 0x6c,
	0x61, 0x6e, 0x74, 0x54, 0x72, 0x65, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15,
	0x2e, 0x74, 0x72, 0x65, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x72, 0x65, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x54, 0x72,
	0x65, 0x65, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x2e, 0x74, 0x72, 0x65,
	0x65, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x72, 0x65, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x15, 0x2e, 0x74, 0x72, 0x65, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x72, 0x65, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x09, 0x47, 0x65, 0x74,
	0x4d, 0x79, 0x54, 0x72, 0x65, 0x65, 0x12, 0x14, 0x2e, 0x74, 0x72, 0x65, 0x65, 0x2e, 0x47, 0x65,
	0x74, 0x54, 0x72, 0x65, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x74,
	0x72, 0x65, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x72, 0x65, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4d, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x54, 0x72, 0x65, 0x65,
	0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x12, 0x1b, 0x2e, 0x74, 0x72, 0x65, 0x65, 0x2e, 0x47,
	0x65, 0x74, 0x54, 0x72, 0x65, 0x65, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x74, 0x72, 0x65, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x54,
	0x72, 0x65, 0x65, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x0a, 0x47, 0x72, 0x6f, 0x77, 0x74, 0x68, 0x54, 0x72,
	0x65, 0x65, 0x12, 0x13, 0x2e, 0x74, 0x72, 0x65, 0x65, 0x2e, 0x47, 0x72, 0x6f, 0x77, 0x74, 0x68,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x74, 0x72, 0x65, 0x65, 0x2e, 0x47,
	0x72, 0x6f, 0x77, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x0a, 0x5a, 0x08, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_schema_tree_proto_rawDescOnce sync.Once
	file_schema_tree_proto_rawDescData = file_schema_tree_proto_rawDesc
)

func file_schema_tree_proto_rawDescGZIP() []byte {
	file_schema_tree_proto_rawDescOnce.Do(func() {
		file_schema_tree_proto_rawDescData = protoimpl.X.CompressGZIP(file_schema_tree_proto_rawDescData)
	})
	return file_schema_tree_proto_rawDescData
}

var file_schema_tree_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_schema_tree_proto_goTypes = []interface{}{
	(*PlantTreeRequest)(nil),       // 0: tree.PlantTreeRequest
	(*GetTreeRequest)(nil),         // 1: tree.GetTreeRequest
	(*GetTreeResponse)(nil),        // 2: tree.GetTreeResponse
	(*GetTreeRankingRequest)(nil),  // 3: tree.GetTreeRankingRequest
	(*GetTreeRankingResponse)(nil), // 4: tree.GetTreeRankingResponse
	(*Tree)(nil),                   // 5: tree.Tree
	(*GrowthRequest)(nil),          // 6: tree.GrowthRequest
	(*GrowthResponse)(nil),         // 7: tree.GrowthResponse
}
var file_schema_tree_proto_depIdxs = []int32{
	5, // 0: tree.GetTreeResponse.tree:type_name -> tree.Tree
	5, // 1: tree.GetTreeRankingResponse.ranking:type_name -> tree.Tree
	5, // 2: tree.GrowthResponse.tree:type_name -> tree.Tree
	0, // 3: tree.TreeService.InitTree:input_type -> tree.PlantTreeRequest
	0, // 4: tree.TreeService.PlantTree:input_type -> tree.PlantTreeRequest
	1, // 5: tree.TreeService.GetTreeByUserId:input_type -> tree.GetTreeRequest
	1, // 6: tree.TreeService.GetMyTree:input_type -> tree.GetTreeRequest
	3, // 7: tree.TreeService.GetTreeRanking:input_type -> tree.GetTreeRankingRequest
	6, // 8: tree.TreeService.GrowthTree:input_type -> tree.GrowthRequest
	2, // 9: tree.TreeService.InitTree:output_type -> tree.GetTreeResponse
	2, // 10: tree.TreeService.PlantTree:output_type -> tree.GetTreeResponse
	2, // 11: tree.TreeService.GetTreeByUserId:output_type -> tree.GetTreeResponse
	2, // 12: tree.TreeService.GetMyTree:output_type -> tree.GetTreeResponse
	4, // 13: tree.TreeService.GetTreeRanking:output_type -> tree.GetTreeRankingResponse
	7, // 14: tree.TreeService.GrowthTree:output_type -> tree.GrowthResponse
	9, // [9:15] is the sub-list for method output_type
	3, // [3:9] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_schema_tree_proto_init() }
func file_schema_tree_proto_init() {
	if File_schema_tree_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_schema_tree_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlantTreeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_tree_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTreeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_tree_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTreeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_tree_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTreeRankingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_tree_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTreeRankingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_tree_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tree); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_tree_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrowthRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_tree_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrowthResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_schema_tree_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_schema_tree_proto_goTypes,
		DependencyIndexes: file_schema_tree_proto_depIdxs,
		MessageInfos:      file_schema_tree_proto_msgTypes,
	}.Build()
	File_schema_tree_proto = out.File
	file_schema_tree_proto_rawDesc = nil
	file_schema_tree_proto_goTypes = nil
	file_schema_tree_proto_depIdxs = nil
}
