// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package register

import (
	"github.com/Kurichi/plesio-monorepo/services/bff/handler/item"
	"github.com/Kurichi/plesio-monorepo/services/bff/handler/mission"
	"github.com/Kurichi/plesio-monorepo/services/bff/handler/tree"
	"github.com/Kurichi/plesio-monorepo/services/bff/handler/user"
	"github.com/Kurichi/plesio-monorepo/services/bff/middleware"
	"github.com/Kurichi/plesio-monorepo/services/bff/pkg/firebase"
	"github.com/labstack/echo/v4"
	"google.golang.org/grpc"
)

// Injectors from wire.go:

func New(clientConnInterface grpc.ClientConnInterface) *echo.Echo {
	treeServiceClient := NewTreeClient()
	treeClient := tree.NewTreeClient(treeServiceClient)
	userServiceClient := NewUserClient()
	userClient := user.NewUserClient(userServiceClient, treeServiceClient)
	itemServiceClient := NewItemClient()
	itemClient := item.NewItemClient(itemServiceClient)
	missionServiceClient := NewMissionClient()
	missionClient := mission.NewMissionClient(missionServiceClient, itemServiceClient)
	app := firebase.InitializeFirebaseApp()
	client := firebase.InitializeFBAuthClient(app)
	authController := middleware.NewAuthController(client)
	echoEcho := Register(treeClient, userClient, itemClient, missionClient, authController)
	return echoEcho
}
