// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package register

import (
	"google.golang.org/grpc"
)

// Injectors from wire.go:

func New() *grpc.Server {
	server := Register()
	return server
}
