// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package register

import (
	"github.com/Kurichi/plesio-monorepo/services/tree/adapter/api"
	"github.com/Kurichi/plesio-monorepo/services/tree/usecase"
	"google.golang.org/grpc"
)

// Injectors from wire.go:

func New() *grpc.Server {
	treeUsecase := usecase.NewTreeUsecase()
	treeServiceServer := api.NewTreeHandler(treeUsecase)
	server := Register(treeServiceServer)
	return server
}
